export const exerciseLibrary = [
  { name: "Romanian Deadlift", aliases: ["rdl"], category: "hinge" },
  { name: "Barbell Romanian Deadlift", aliases: ["barbell rdl"], category: "hinge" },
  { name: "Dumbbell Romanian Deadlift", aliases: ["db rdl", "dumbbell rdl"], category: "hinge" },
  { name: "Single Leg Romanian Deadlift", aliases: ["single leg rdl", "sl rdl"], category: "hinge" },
  { name: "B-Stance Romanian Deadlift", aliases: ["b stance rdl", "kickstand rdl"], category: "hinge" },
  { name: "Snatch Grip Romanian Deadlift", aliases: ["snatch grip rdl"], category: "hinge" },
  { name: "Tempo Romanian Deadlift", aliases: ["tempo rdl"], category: "hinge" },
  { name: "Deficit Romanian Deadlift", aliases: ["deficit rdl"], category: "hinge" },
  { name: "Back Squat", aliases: ["squat"], category: "squat" },
  { name: "Front Squat", aliases: ["fs"], category: "squat" },
  { name: "Pause Back Squat", aliases: ["paused squat"], category: "squat" },
  { name: "Tempo Back Squat", aliases: ["tempo squat"], category: "squat" },
  { name: "Overhead Squat", aliases: ["ohs"], category: "squat" },
  { name: "Deadlift", aliases: ["dl"], category: "hinge" },
  { name: "Clean Deadlift", aliases: ["clean dl"], category: "hinge" },
  { name: "Snatch Deadlift", aliases: ["snatch dl"], category: "hinge" },
  { name: "Clean Pull", aliases: ["clean high pull"], category: "pull" },
  { name: "Snatch Pull", aliases: ["snatch high pull"], category: "pull" },
  { name: "Snatch", aliases: [], category: "olympic" },
  { name: "Power Snatch", aliases: [], category: "olympic" },
  { name: "Hang Snatch", aliases: [], category: "olympic" },
  { name: "Block Snatch", aliases: [], category: "olympic" },
  { name: "Clean and Jerk", aliases: ["c&j", "cj"], category: "olympic" },
  { name: "Clean", aliases: [], category: "olympic" },
  { name: "Power Clean", aliases: [], category: "olympic" },
  { name: "Hang Clean", aliases: [], category: "olympic" },
  { name: "Jerk", aliases: [], category: "olympic" },
  { name: "Split Jerk", aliases: [], category: "olympic" },
  { name: "Push Press", aliases: [], category: "press" },
  { name: "Strict Press", aliases: ["ohp"], category: "press" },
  { name: "Bench Press", aliases: ["bench"], category: "press" },
  { name: "Close Grip Bench Press", aliases: ["cgbp"], category: "press" },
  { name: "Pull-Up", aliases: ["pullup"], category: "upper" },
  { name: "Chin-Up", aliases: ["chinup"], category: "upper" },
  { name: "Bent Over Row", aliases: ["barbell row"], category: "upper" },
  { name: "Dumbbell Row", aliases: ["db row"], category: "upper" },
  { name: "Walking Lunge", aliases: ["lunges"], category: "single-leg" },
  { name: "Bulgarian Split Squat", aliases: ["bss"], category: "single-leg" },
  { name: "Step-Up", aliases: ["step up"], category: "single-leg" },
  { name: "Hip Thrust", aliases: [], category: "glutes" },
  { name: "Glute Bridge", aliases: [], category: "glutes" },
  { name: "Plank", aliases: [], category: "core" },
  { name: "Hanging Leg Raise", aliases: ["hlr"], category: "core" },
  { name: "Bike", aliases: ["air bike", "assault bike"], category: "cardio" },
  { name: "Row", aliases: ["rower", "erg"], category: "cardio" },
  { name: "Run", aliases: ["jog"], category: "cardio" },
  { name: "Ski Erg", aliases: ["skierg"], category: "cardio" },
  { name: "Burpee", aliases: ["burpees"], category: "cardio" },
];

export const exerciseSuggestions = [...new Set(exerciseLibrary.flatMap((exercise) => [
  exercise.name,
  ...exercise.aliases.map((alias) => `${alias.toUpperCase()} - ${exercise.name}`),
]))].sort();
